openapi: 3.1.0
info:
  title: EPS API
  version: 0.1.1
  termsOfService: 'https://example.com/terms/'
  contact:
    name: Contact Eko
    email: info@eko.co.in
    url: 'http://example.com/contact'
  license:
    name: Apache 2.0
    url: 'http://www.apache.org/licenses/LICENSE-2.0.html'
  x-logo:
    url: 'https://ekoin.netlify.app/images/logo.svg'
  description:
    $ref: description.md

externalDocs:
  description: Checkout the developer portal to read the detailed guides
  url: 'https://developers.eko.in'

tags:
  - name: Agent Management
    description: Onboard your agents/users and manage services for them.
  - name : Customers
    description: Create and verify customers. Perform recurring transactions and add multiple recipients to the same customer.
  - name: Customer KYC
    description: Upgrade customer KYC status and enable higher amount of transactions per month.
  - name: Recipients
    description: Manage recipients for your customers to transfer money to.
  - name: Transaction
    description: Money Transfer APIs.
  - name: Banks
    description: Get bank information.
  - name: Token
    description: Accept real-time cash-payment for your digital services.
  - name: Partner Account
    description: Settle your funds into your bank account.
  - name: Fund Settlement
    description: sample description
  - name: AePS Fund Settlement
    description: sample description

servers:
- url: https://staging.eko.in:25004/ekoicici/v1

paths:
  /user/services:
    $ref: ./paths/user@services.yaml
  /user/request/otp:
    $ref: ./paths/user@request@otp.yaml
  /user/verify:
    $ref: ./paths/user@verify.yaml
  /user/onboard:
    $ref: ./paths/user@onboard.yaml
  /user/service/activate:
    $ref: ./paths/user@service@activate.yaml
  /user/services/user_code:{user_code}:
    $ref: ./paths/user@services@user_code:{user_code}.yaml
  /onboard:
    $ref: ./paths/onboard.yaml
  /customers/mobile_number:{mobile_number}:
    $ref: ./paths/customers@mobile_number:{mobile_number}.yaml
